### ISSUE TITLE
Build as non-EON compiled project

### ISSUE THREAD

**Issue by quicksketch** [edgeimpulse/multi-impulse-deployment-block#3]
Is this script capable (or planning to be capable) of compiling a non-EON multi impulse?

I'm fairly new to Edge Impulse but from the [documentation on multi-impulses](https://docs.edgeimpulse.com/docs/tutorials/advanced-inferencing/multi-impulse), the naming the `tflite_model_compiled.cpp` file indicates the generated output is EON compiled rather than tflite-compatible. For me, memory usage is not as important as processing time, and a non-EON compilation would be preferable.

**Comment by AIWintermuteAI** [comment]
Preliminary support is added in
https://github.com/edgeimpulse/multi-impulse-deployment-block/pull/4
and more work is underway in https://github.com/edgeimpulse/multi-impulse-deployment-block/pull/6

**Comment by quicksketch** [comment]
Awesome, thanks for the update!
